name: mc-pasman
version: '4.8.28-33'
summary: Midnight Commander
description: |
  Midnight Commander. https://midnight-commander.org

  This build has restricted access.
  Enable access to directories:

    sudo snap connect mc-pasman:home  
    sudo snap connect mc-pasman:system-backup          
    sudo snap connect mc-pasman:removable-media 

  Applications:
  
    mc-pasman
    mc-pasman.mcedit
    mc-pasman.mcview
    mc-pasman.mcdiff:
  
  Configs:

    ~/snap/mc-pasman/current/.config

  Based on core22.


base: core22
grade: stable
confinement: strict
compression: lzo

plugs:


apps:
  mc-pasman:
    command: bin/mc
    plugs: [ home, system-backup, removable-media, network ]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

  mcedit:
    command: bin/mcedit
    plugs: [ home, system-backup, removable-media, network ]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

  mcview:
    command: bin/mcview
    plugs: [ home, system-backup, removable-media, network ]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

  mcdiff:
    command: bin/mcdiff
    plugs: [ home, system-backup, removable-media, network ]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8



parts:
  mc:
    source: http://ftp.midnight-commander.org/mc-4.8.28.tar.xz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/snap/mc-pasman/current
      - --localstatedir=$SNAP_USER_DATA
      
    build-packages:
      - build-essential
      - autoconf
      - libglib2.0-dev
      - libslang2-dev
      - gettext
      - autopoint
      - libgpm-dev
      - libssh2-1-dev
      - mc

    stage-packages:
      - libgpm2
      - libslang2
      - libssh2-1
      - gettext

    prime:
      - -var
      - -share/info
      - -share/man
      - -usr/share/doc
      - -usr/share/icons
      - -usr/share/man
      - -snap

    organize:
      snap/mc-pasman/current/etc: etc
      snap/mc-pasman/current/bin: bin
      snap/mc-pasman/current/share: share
      snap/mc-pasman/current/libexec: libexec
